### PR TITLE
Added optional config parameters for the lock device name, ring to open and continuous mode

### PR DESCRIPTION
**Pull request by felixmueller**
Hi Lukas,

thank you for the great plugin, it works like expected!

I had the problem, that die Nuki Bridge API always returns "Opener" as my opener device name, even if I change the device name in the Nuki App (device name and display name).

I added an optional config parameter to override the device name. Additionally, I added the possibility to change the ring to open and continuous mode switch device names.

If you have a more elegant solution for this, please feel free to reject my pull request 😊

Thanks a lot!

Cheers
Felix

### CODE REVIEW

**Comment by lukasroegner** [comment]
Hi Felix,
Thank you for your contribution. Is it necessary to add those properties? In the Home app, I'm able to change the names for the accessories as well as the services of the accessories (if you use iOS 13, the switches are grouped in a single accessory).

**Comment by felixmueller** [comment]
Hi Lukas,
in my experience, the Accessory names from Homebridge plugins are reset once Homebridge is restarted. Maybe this is not the case for your plugin, because the Accessories are cached?
I will try to change the names via Home App later today and then post my feedback.
Cheers
Felix

**Comment by lukasroegner** [comment]
When accessories and services are created they get a default name (accessory: name from Nuki Bridge, services: name from code). Accessories are not recreated when homebridge is restarted (unless they have been cached, which I think is enabled by default in homebridge).

**Comment by felixmueller** [comment]
Hi Lukas,
thank you for the clarification. I think I will wait until the official iOS 13 release on Thursday and then check again how the accessories in the Home App look like.
If there is anything that needs to be changed, I will update it here.
Cheers
Felix

**Comment by felixmueller** [comment]
I installed the latest release and successfully renamed the LockAccessory inside the Home App.
If the SwitchAccessory for the 2 settings ("[Lock Name] Settings") can be renamed, too, there is no need for my change anymore. I will try it on iOS 13.1 on Tuesday.
I will close this pull request for now.

**Pull request closed without merging**
